#!/usr/bin/env bash
# install nginx and make the default page to say Hello World!

apt-get -y install nginx > /dev/null
ufw allow 'Nginx HTTP' > /dev/null 2>&1
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html > /dev/null
