#!/usr/bin/env bash
# Configure a new ubuntu server to respond with a custom HTTP header
# # As to be run as root

apt-get update > /dev/null
apt-get -y install nginx > /dev/null
ufw allow 'Nginx HTTP' > /dev/null 2>&1

hostname=$(hostname)


echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	add_header X-Served-By $hostname;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}

}" | tee /etc/nginx/sites-available/default > /dev/null

systemctl restart nginx
