#!/usr/bin/env bash
# This script displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009

ps aux | awk '/bash/ {print $1, $2, $3, $4, $5, $6, $7, $8, $10, $11}'
