#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

h=0

while [ $h -le 12 ]
do
printf "Hour: %d\n" $h
  min=1
  while [ $min -le 59 ]
  do
    printf "%d\n" $min
    min=$((min+1))
  done
  h=$((h+1))
done
